#!/usr/bin/env python3
"""Regenerate the index tables at the top of the project-context registries.

`DECISIONS.md` and `LEARNINGS.md` open with a table of every entry, generated
from the entries themselves (see `D-019`). Run this after adding an entry or
changing a status:

    python3 scripts/context_index.py            # rewrite both registries
    python3 scripts/context_index.py --check    # exit 1 if either is stale

The index is derived, never hand-edited: anything between the markers is
replaced. Entry headings are the statement column, so they carry weight.

The registry states a decision's status in two forms and this reads both — see
`status_of`. Either mode exits 1 when an entry's status cannot be read, and the
table cell says so out loud; nothing is ever assumed. A status guessed as
`accepted` on a superseded decision is the failure this parser exists to stop.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path
from typing import NamedTuple

START = "<!-- context-index:start -->"
END = "<!-- context-index:end -->"

# The vocabulary `DECISIONS.md` declares in its own preamble. A status outside
# it is a hole in the record, not a new value to pass through.
STATUSES = ("proposed", "accepted", "superseded")

# Rendered where a status could not be read. Loud on purpose: someone scanning
# the table must see a hole rather than a status, and bold survives the table.
UNREADABLE = "**status unreadable**"

REGISTRIES = (
    {
        "file": "DECISIONS.md",
        "prefix": "D",
        "columns": ("Decision", "Status"),
        "field": "Status",
        # No default, deliberately. The `accepted` fallback that used to live
        # here is what let `D-033` and `D-050` — both superseded in their own
        # bodies — sit in the index as live guidance.
        "blurb": "Index — generated by `scripts/context_index.py`; do not hand-edit.",
    },
    {
        "file": "LEARNINGS.md",
        "prefix": "L",
        "columns": ("Learning", "Applies to"),
        "field": "Scope",
        # An em dash here is honest: newer learnings state no scope field, and
        # a blank claims nothing. Unlike a status, it cannot mislead.
        "default": "—",
        "blurb": (
            "Index — generated by `scripts/context_index.py`; do not hand-edit.\n"
            "Open the entries this index puts in scope rather than reading the\n"
            "registry end to end."
        ),
    },
)


class Entry(NamedTuple):
    ident: str
    title: str
    status: str      # normalised into STATUSES, or "" when unreadable
    status_raw: str  # what the registry actually said, so a report can quote it
    scope: str


def slug(title: str) -> str:
    """GitHub heading anchor: lowercase, drop punctuation, spaces to hyphens."""
    cleaned = re.sub(r"[^\w\s-]", "", title.lower())
    return re.sub(r"[\s_]+", "-", cleaned.strip())


def list_field(body: str, name: str) -> str:
    """The value of a `- Name:` list field, with wrapped lines joined."""
    hit = re.search(r"^- %s:\s*(.+?)(?=\n- |\n\n|\Z)" % name, body, re.M | re.S)
    return " ".join(hit.group(1).split()) if hit else ""


def status_of(body: str) -> tuple[str, str]:
    """Read an entry's status, in either form the registry uses.

    Older entries (`D-001`-`D-029`) carry a `- Status:` list field. Newer ones
    (`D-030` onward) open the body with the prose form — a backticked status,
    the date's middle dot, then optionally an em dash and why:

        `superseded` · 2026-09-03 — **by `D-051` the same day.**

    Both are Daren's record and neither is going to be rewritten into the
    other, so the parser reads both. Returns `(status, raw)`: the status
    lowercased and checked against `STATUSES`, or `""` when the registry said
    something unrecognised, alongside the raw text for the report.
    """
    raw = list_field(body, "Status")
    if not raw:
        opening = next((line for line in body.splitlines() if line.strip()), "")
        # Require the status to be followed by the date separator, an em dash,
        # or the end of the line, so a body that merely opens with a code span
        # is not mistaken for one.
        prose = re.match(r"\s*`([^`]+)`\s*(?:[·—]|$)", opening)
        # No match means the entry states no status at all, in either form —
        # reported as such rather than by quoting an arbitrary body line.
        raw = prose.group(1) if prose else ""

    words = raw.strip().strip("`").split()
    word = words[0].strip("`.,;:").lower() if words else ""
    return (word if word in STATUSES else ""), raw


def entries(text: str, prefix: str) -> list[Entry]:
    found = []
    heads = list(re.finditer(r"^## (%s-\d+): (.+)$" % prefix, text, re.M))
    for index, match in enumerate(heads):
        end = heads[index + 1].start() if index + 1 < len(heads) else len(text)
        body = text[match.end():end]
        status, raw = status_of(body)
        found.append(Entry(match.group(1), match.group(2).strip(), status, raw,
                           list_field(body, "Scope")))
    return found


def render(text: str, spec: dict, problems: list[str]) -> str:
    rows = entries(text, spec["prefix"])
    lines = [START, spec["blurb"], "", f"| ID | {spec['columns'][0]} | {spec['columns'][1]} |", "| --- | --- | --- |"]
    for row in rows:
        if spec["field"] == "Status":
            value = f"`{row.status}`" if row.status else UNREADABLE
            if not row.status:
                quoted = row.status_raw[:60] + ("…" if len(row.status_raw) > 60 else "")
                said = (f"the entry says {quoted!r}, which is not a status" if quoted
                        else "the entry states no status in either form")
                problems.append(f"{spec['file']}: {row.ident} — {said}")
        else:
            value = row.scope or spec["default"]
        lines.append(f"| [`{row.ident}`](#{slug(row.ident + ' ' + row.title)}) | {row.title} | {value} |")
    lines.append(END)
    return "\n".join(lines)


def rebuild(path: Path, spec: dict, problems: list[str]) -> str:
    text = path.read_text(encoding="utf-8")
    block = render(text, spec, problems)

    first = re.search(r"^## ", text, re.M)
    if not first:
        return text
    head, rest = text[:first.start()], text[first.start():]

    # Drop any previous index first — a marked block, an unmarked one left by an
    # earlier generation, or both. Only the prose above the first entry is kept,
    # so this is self-healing rather than order-dependent.
    if START in head and END in head:
        head = head[:head.index(START)] + head[head.index(END) + len(END):]
    kept = [
        line for line in head.splitlines()
        if not line.startswith("|") and not line.startswith("Index —")
    ]
    head = re.sub(r"\n{3,}", "\n\n", "\n".join(kept)).rstrip("\n")
    return head + "\n\n" + block + "\n\n" + rest


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="report staleness instead of writing")
    parser.add_argument("--context", default="project-context", help="path to the project-context directory")
    args = parser.parse_args(argv)

    context = Path(args.context)
    stale: list[str] = []
    problems: list[str] = []
    for spec in REGISTRIES:
        path = context / spec["file"]
        if not path.is_file():
            print(f"missing: {path}", file=sys.stderr)
            continue
        current = path.read_text(encoding="utf-8")
        updated = rebuild(path, spec, problems)
        count = len(entries(current, spec["prefix"]))
        if current == updated:
            print(f"{spec['file']}: current ({count} entries)")
            continue
        stale.append(spec["file"])
        if args.check:
            print(f"{spec['file']}: STALE ({count} entries)")
        else:
            path.write_text(updated, encoding="utf-8")
            print(f"{spec['file']}: regenerated ({count} entries)")

    # An unreadable status is reported in both modes and fails the run. The
    # index is still written, so one malformed entry cannot hold the other fifty
    # hostage — but it lands as UNREADABLE, and the non-zero exit makes it a
    # gate rather than a line of output somebody scrolls past.
    if problems:
        print(f"\nUNREADABLE STATUS ({len(problems)}):", file=sys.stderr)
        for line in problems:
            print(f"  {line}", file=sys.stderr)
        print(
            "\nThese are rendered as %s in the index, never guessed.\n"
            "Give each one a status of %s, either as a `- Status:` list field\n"
            "or as the prose opening line `` `status` \u00b7 YYYY-MM-DD ``."
            % (UNREADABLE, ", ".join("`%s`" % s for s in STATUSES)),
            file=sys.stderr,
        )

    if args.check and stale:
        print("\nIndex is stale. Run: python3 scripts/context_index.py", file=sys.stderr)
    return 1 if (problems or (args.check and stale)) else 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
