#!/usr/bin/env python3
"""Regenerate the index tables at the top of the project-context registries.

`DECISIONS.md` and `LEARNINGS.md` open with a table of every entry, generated
from the entries themselves (see `D-019`). Run this after adding an entry or
changing a status:

    python3 scripts/context_index.py            # rewrite both registries
    python3 scripts/context_index.py --check    # exit 1 if either is stale

The index is derived, never hand-edited: anything between the markers is
replaced. Entry headings are the statement column, so they carry weight.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

START = "<!-- context-index:start -->"
END = "<!-- context-index:end -->"

REGISTRIES = (
    {
        "file": "DECISIONS.md",
        "prefix": "D",
        "columns": ("Decision", "Status"),
        "field": "Status",
        "default": "`accepted`",
        "blurb": "Index — generated by `scripts/context_index.py`; do not hand-edit.",
    },
    {
        "file": "LEARNINGS.md",
        "prefix": "L",
        "columns": ("Learning", "Applies to"),
        "field": "Scope",
        "default": "—",
        "blurb": (
            "Index — generated by `scripts/context_index.py`; do not hand-edit.\n"
            "Open the entries this index puts in scope rather than reading the\n"
            "registry end to end."
        ),
    },
)


def slug(title: str) -> str:
    """GitHub heading anchor: lowercase, drop punctuation, spaces to hyphens."""
    cleaned = re.sub(r"[^\w\s-]", "", title.lower())
    return re.sub(r"[\s_]+", "-", cleaned.strip())


def entries(text: str, prefix: str) -> list[tuple[str, str, str, str]]:
    found = []
    heads = list(re.finditer(r"^## (%s-\d+): (.+)$" % prefix, text, re.M))
    for index, match in enumerate(heads):
        end = heads[index + 1].start() if index + 1 < len(heads) else len(text)
        body = text[match.end():end]

        def field(name: str) -> str:
            hit = re.search(r"^- %s:\s*(.+?)(?=\n- |\n\n|\Z)" % name, body, re.M | re.S)
            return " ".join(hit.group(1).split()) if hit else ""

        found.append((match.group(1), match.group(2).strip(), field("Status"), field("Scope")))
    return found


def render(text: str, spec: dict) -> str:
    rows = entries(text, spec["prefix"])
    lines = [START, spec["blurb"], "", f"| ID | {spec['columns'][0]} | {spec['columns'][1]} |", "| --- | --- | --- |"]
    for ident, title, status, scope in rows:
        value = (status if spec["field"] == "Status" else scope) or spec["default"]
        lines.append(f"| [`{ident}`](#{slug(ident + ' ' + title)}) | {title} | {value} |")
    lines.append(END)
    return "\n".join(lines)


def rebuild(path: Path, spec: dict) -> str:
    text = path.read_text(encoding="utf-8")
    block = render(text, spec)

    first = re.search(r"^## ", text, re.M)
    if not first:
        return text
    head, rest = text[:first.start()], text[first.start():]

    # Drop any previous index first — a marked block, an unmarked one left by an
    # earlier generation, or both. Only the prose above the first entry is kept,
    # so this is self-healing rather than order-dependent.
    if START in head and END in head:
        head = head[:head.index(START)] + head[head.index(END) + len(END):]
    kept = [
        line for line in head.splitlines()
        if not line.startswith("|") and not line.startswith("Index —")
    ]
    head = re.sub(r"\n{3,}", "\n\n", "\n".join(kept)).rstrip("\n")
    return head + "\n\n" + block + "\n\n" + rest


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="report staleness instead of writing")
    parser.add_argument("--context", default="project-context", help="path to the project-context directory")
    args = parser.parse_args(argv)

    context = Path(args.context)
    stale = []
    for spec in REGISTRIES:
        path = context / spec["file"]
        if not path.is_file():
            print(f"missing: {path}", file=sys.stderr)
            continue
        current = path.read_text(encoding="utf-8")
        updated = rebuild(path, spec)
        count = len(entries(current, spec["prefix"]))
        if current == updated:
            print(f"{spec['file']}: current ({count} entries)")
            continue
        stale.append(spec["file"])
        if args.check:
            print(f"{spec['file']}: STALE ({count} entries)")
        else:
            path.write_text(updated, encoding="utf-8")
            print(f"{spec['file']}: regenerated ({count} entries)")

    if args.check and stale:
        print("\nIndex is stale. Run: python3 scripts/context_index.py", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
